; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_ldf_mode = deep+

; Forțăm compilatorul să includă aceste foldere la căutarea fișierelor .h
build_flags = 
    -I include
    -I lib/sim_plant
    -I lib/algo_pid
    -I lib/ctrl_stdio
    -I lib/srv_temp
    -I lib/dd_pot
    -I lib/dd_heater
    -I lib/ctrl_tasks
    -I lib/srv_scheduler
    -Wl,-u,vfprintf -lprintf_flt

lib_deps =
    feilipu/FreeRTOS @ ^11.1.0-3
