#ifndef CONFIGS_H
#define CONFIGS_H

#define BAUDRATE 115200

// Define constants for the system
#define LED_BLUE_PIN 6    // led2 (blue) -> r2 -> mega:6
#define LED_GREEN_PIN 7   // led1 (green) -> r1 -> mega:7
#define LCD_COLS 16
#define LCD_ROWS 2
#define LCD_ADDR 0x27

#define INPUT_BUFFER_SIZE 100
#define USER_PASSWORD "1234"

#define KEYPAD_ROWS 4
#define KEYPAD_COLS 4

#define WAIT_TIME_MS 3000

#define BUTTON_PIN 4    // btn1 -> mega:4 (yellow)
#define BUTTON_UP_PIN 3    // btn2 -> mega:3 (red)
#define BUTTON_DOWN_PIN 5  // btn3 -> mega:5 (grey)
#define BUTTON_DEBOUNCE_DELAY 100 // ms

#define DEFAULT_BLINK_FREQUENCY 500 // ms
#define MIN_BLINK_FREQUENCY 100 // ms
#define MAX_BLINK_FREQUENCY 2000 // ms
#define BLINK_FREQUENCY_STEP 100 // ms

#define BUTTON_LED_TASK_OFFSET_MS       1
#define BUTTON_LED_TASK_RECURRANCE_MS   50

#define BLUE_LED_TASK_OFFSET_MS             5
#define BLUE_LED_TASK_RECURRANCE_MS         (MIN_BLINK_FREQUENCY / 2)

#define INC_DEC_LED_TASK_OFFSET_MS         2
#define INC_DEC_LED_TASK_RECURRANCE_MS     (BLINK_FREQUENCY_STEP / 2)

#define FREERTOS_FIRST_RECURRANCE_MS        10
#define FREERTOS_BUTTON_DEBOUNCE_DELAY_MS   20
#define FREERTOS_FIRST_ON_TIME_MS           1000
#define FREERTOS_FIRST_TASK_STACK_SIZE     128
#define FREERTOS_FIRST_TASK_PRIORITY        1

#define FREERTOS_SECOND_TASK_STACK_SIZE    192
#define FREERTOS_SECOND_TASK_PRIORITY      1
#define FREERTOS_SECOND_SEND_INTERVAL_MS   50
#define FREERTOS_SECOND_LED_ON_MS          300
#define FREERTOS_SECOND_LED_OFF_MS         500
#define FREERTOS_SECOND_COUNTER_START_VALUE 0
#define FREERTOS_SECOND_SEQUENCE_FIRST_VALUE 1

#define FREERTOS_THIRD_TASK_STACK_SIZE     256
#define FREERTOS_THIRD_TASK_PRIORITY       1
#define FREERTOS_THIRD_RECURRANCE_MS       200

#define FREERTOS_QUEUE_SIZE                64
#define FREERTOS_QUEUE_TERMINATOR_VALUE    0
#define FREERTOS_QUEUE_READ_TIMEOUT_TICKS  0

#define TASKS_IDLE_STATUS_PRINT_MS         500

typedef enum {
    KEYPAD_PIN_1=23,
    KEYPAD_PIN_2=25,
    KEYPAD_PIN_3=27,  
    KEYPAD_PIN_4=29,
    KEYPAD_PIN_5=31,
    KEYPAD_PIN_6=33,
    KEYPAD_PIN_7=35,
    KEYPAD_PIN_8=37,     
}keypad_pin_t;

#endif // CONFIGS_H